# Generated by Django 4.2.2 on 2025-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
